apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller
spec:
  selector:
    matchLabels:
      app: cloud-controller
  template:
    metadata:
      labels:
        app: cloud-controller
    spec:
      serviceAccountName: cloud-controller
      containers:
        - name: cloud-controller
          image: io.corestack.kubeedge/cloud-controller:0.1
          imagePullPolicy: IfNotPresent
